### ISSUE TITLE
docker-compose up -d ERROR: manifest unknown

### ISSUE THREAD

**Issue by ziyu211** [CloudOrc/SolidUI#109]
### Your environment

0.2.0

### Describe your questions

(base) [root@ns3yafx1dwrbda2a docker]# docker image list
REPOSITORY         TAG       IMAGE ID       CREATED          SIZE
solidui-web        0.2.0     eb3e97b44893   16 minutes ago   107MB
solidui-entrance   0.2.0     bfb6f5e463c7   17 minutes ago   271MB

### Some logs info or acctch file

(base) [root@ns3yafx1dwrbda2a docker]# docker-compose up -d
Pulling solidui-entrance (ghcr.io/cloudorc/solidui/solidui-entrance:0.2.0)...
ERROR: manifest unknown

**Comment by dlimeng** [comment]
refer to https://github.com/CloudOrc/SolidUI-Doc/blob/main/zh_CN/%E5%BC%80%E5%8F%91%E6%96%87%E6%A1%A3/Docker%E9%95%9C%E5%83%8F/README.md

**Comment by dlimeng** [comment]
The docker-compose.yml environment variable.env is modified to a local image  
<img width="616" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/db32b423-f474-4859-8ff6-05ed6971b411">

**Comment by ziyu211** [comment]
![123](https://github.com/CloudOrc/SolidUI/assets/52304716/3b2c22e5-6be2-45e3-9634-37a1cbea3323)

**Comment by ziyu211** [comment]
API_PORT=5010
WEB_PORT=5110
SNAKEMQ_PORT=8765
SNAKEMQ_LISTENER=0.0.0.0
SNAKEMQ_CONNECTOR=soliduimodelui

**Comment by ziyu211** [comment]
这里的还保留原来的127.0.0.1可否

**Comment by ziyu211** [comment]
what's
![123](https://github.com/CloudOrc/SolidUI/assets/52304716/223ac559-43b0-4268-a75b-2eeed46af4c5)
![3456](https://github.com/CloudOrc/SolidUI/assets/52304716/ee91155e-323e-4db2-8a14-a8bdf917f1ff)

**Comment by ziyu211** [comment]
change docker network
![123](https://github.com/CloudOrc/SolidUI/assets/52304716/7059ecf1-a82a-4620-8e9b-324e83ff0049)
