### ISSUE TITLE
[Feature][Deploy] Support kubernetes deployment

### ISSUE THREAD

**Issue by jacktao007** [CloudOrc/SolidUI#115]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

Support kubernetes deployment 

### Description

Support kubernetes deployment

### Use case

#26 

### Solutions

Deploy SolidUI using Helm Charts technology.

![5d3fb20e96235ae07bf2e7ae99823177_260bc6ca81884a3bbb742bbb0c27303f](https://github.com/CloudOrc/SolidUI/assets/1073365/98f987dd-34a8-4512-9dbd-47a77cd97c51)

<img width="1533" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/f48044db-3da5-4dcc-ab13-21f49b46e68f">
写在deployment菜单，新开一个markdown 写k8s部署，中文和英文

Write it under the deployment menu, start a new markdown for k8s deployment, both in Chinese and English.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by dlimeng** [comment]
<img width="1533" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/f48044db-3da5-4dcc-ab13-21f49b46e68f">
写在deployment菜单，新开一个markdown 写k8s部署，中文和英文
Write it under the deployment menu, start a new markdown for k8s deployment, both in Chinese and English.
