### ISSUE TITLE
[Feature][DataSource] Query all data source columns, modify the query list interface

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#119]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

Query all data source columns, modify the query list interface

/solidui/datasource/info   according to the reverse query of dataSourceTypeId in the list, dataSourceTypeName is displayed

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by limingoo** [comment]
I want to address this issue.
