### ISSUE TITLE
[Feature][SolidUI-Web] Right sliding window shrinks

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#133]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

Right sliding window shrinks 
<img width="339" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/bbe19654-86a2-4ccf-8ccd-5d5f83c94f0e">

![Image](https://github.com/CloudOrc/SolidUI/assets/16789827/34afdeb8-3c1c-4d77-b7c1-bfdb05f43904)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by liangxm-swan** [comment]
I will try my best to do it，please assign to me

**Comment by dlimeng** [comment]
The red box is also contracted, all contracted and marked in red leaving white are also contracted.
画红框也收缩，全部收缩标红留白也收缩

<img width="1790" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/6cc0f785-a9b5-4f6d-b2d3-568a57e8c2b5">
