### ISSUE TITLE
[Feature][SolidUI-Web] Design the page, hide the static legends and the legends data tab.

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#141]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

Design the page, hide the static legends and the legends data tab.
<img width="1786" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/c92abd70-011f-434c-953e-ce5d071db6c1">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xjm11** [comment]
1
