### ISSUE TITLE
[Question] No backtracking information on the interface

### ISSUE THREAD

**Issue by ziyu211** [CloudOrc/SolidUI#147]
### Your environment

Docker Compose version v2.20.3
SolidUI:0.2.0

### Describe your questions

Q1.  ...
 No backtracking information on the interface

### Some logs info or acctch file

xxx.log:
````log

<!--日志文字贴到这里-->

````
![1](https://github.com/CloudOrc/SolidUI/assets/52304716/71e91002-72a9-422d-ba0d-3f07ca4149c0)
![2](https://github.com/CloudOrc/SolidUI/assets/52304716/9a12365b-7278-41ee-b1eb-ccb3ece75317)

**Comment by dlimeng** [comment]
Solve the problem of replacing GLM2-6B
