### ISSUE TITLE
[Feature][SolidUI-Web] Pre-set Background Image Feature

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#162]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

1. Show URL background image link
Create in the original way, without making changes.

2. Modify URL background image link
Add an interface to modify the picture URL.  #185 
<img width="1483" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/5c8405f6-2deb-4b6e-ab10-650c8605af7d">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by xjm11** [comment]
come

**Comment by dlimeng** [comment]
这个项目id下有imgae ，弹窗没有显示url
<img width="1519" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/eff368ad-27b8-4cc4-8cdd-4ed6c319417f">
