### ISSUE TITLE
[Feature][SolidUI-Web] Datasource list displays dataSourceTypeName

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#163]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

Replace datasourceTypeId with datasourceTypeName
<img width="1620" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/22a18908-a0c9-42ce-afc9-7b35da7850d0">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by MR-WF** [comment]
ok
