### ISSUE TITLE
[Feature][SolidUI-Entrance] Pre-set Background Image Interface

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#185]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

1.Added image editing functionality to the project management
#162

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by limingoo** [comment]
Let me do this.
