### ISSUE TITLE
[Feature][DataSource] Dev0.1.0 DataSource  test cases and functional tests

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#20]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

1.DataSource test cases
2.DataSource functional tests
3.DataSource Unit testing

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by limingoo** [comment]
I am willing to submit a PR!

**Comment by dlimeng** [comment]
> I am willing to submit a PR!

@limingoo  has been assigned to you, looking forward to your pr

**Comment by dlimeng** [comment]
fix
