### ISSUE TITLE
[Feature][SolidUI-Web] Dev0.2.0 preview optimization 

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#43]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

<img width="1357" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/90ce3ac9-99f3-4e38-b4c1-5cf9d0d81dc2">

preview effect
As shown in the picture, you can view left and right according to the scene-page

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lepen-yang** [comment]
Yes I am willing to submit a PR
