### ISSUE TITLE
[Feature][SolidUI-Web] Dev0.2.0 Design pages, scenes and page optimization

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#44]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

1. The scene supports the right-click floating menu (functions include delete and rename)
2. Scene renaming is underlined in the current name
3. Page renaming is underlined in the current name

https://web.raykite.com/project/edit/b0d603760fba4434b2d984a15b62542d
<img width="293" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/883cc572-401a-4ae1-9a83-8dd4739b84ca">
<img width="285" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/32d9aa6f-8b01-457c-8484-47d365c1ca68">
<img width="268" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/cc4e753e-fc18-4af4-9aa6-ccc0c0e10dc0">

4.add a new scene. After clicking, a scene name will be added by default. For example: scene one, scene two...

5.add a new page, after clicking the button, a new page will be added by default, for example: page 1, page 2

<img width="274" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/e81f892b-d087-4d2b-9333-326ee51d74db">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by lepen-yang** [comment]
I am willing to submit a PR
