### ISSUE TITLE
[Feature][SolidUI-Web] project name modification

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#59]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

1.In the project list -> select a project -> modify the name directly at the project name, press Enter to save the modification

项目名称
创建人
时间
在底部显示这3个

<img width="351" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/e90efa4e-28b0-4faa-aa76-fc3a15a1cbd5">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by MR-WF** [comment]
ok

**Comment by dlimeng** [comment]
icon replacement
<img width="1522" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/569ad1aa-8802-4d33-be4a-a1727ac4d1e4">
