### ISSUE TITLE
[Feature][SolidUI-Website] solidui website  

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#66]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

SolidUI official website, documentation supporting SolidUI  
https://github.com/CloudOrc/SolidUI-Doc  
https://github.com/CloudOrc/SolidUI-Website.git 
dev 分支 是源码 /The dev branch is the source code
main分支 是build之后静态文件 /The main branch is a static file after build
官网域名映射/Official website domain name mapping      [https://website.solidui.top/ ]( https://website.solidui.top/  )

Reference plan
https://docusaurus.io/
https://docusaurus.io/docs/deployment

### 1.The page cannot be found after selecting Chinese, and the Chinese document directory cannot be found when selecting the menu  @15100399015 
选择中文后找不到页面，选择菜单也找不到中文文档目录  Document
<img width="1773" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/7fa3f325-603c-4892-ae29-11576d99b74b">  

### 2.这个背景色修改下，参考咱们的logo 渐变色来实现  @15100399015 
背景色的渐变还是参考咱们的logo 渐变色来实现
To modify this background image, either use the background image of the SolidUI login page, or find a
The gradient of the background color is achieved by referring to our logo gradient color
<img width="1790" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/623e924a-f432-450e-bb5f-9e5a35bc2783">

### 3.文字标题描述，图标都居中 @15100399015 
Text title description, icons are centered
<img width="1779" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/98b07f08-180d-4ebc-a74f-5225073803e5">

参考效果
reference effect
<img width="1779" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/c13d2f2a-e6f4-49bb-8335-7ef2b7864c0b">
https://linkis.incubator.apache.org/

### 4.修改icon背景色，修改成logo的颜色 @15100399015 
Modify the background color of the icon to change it to the color of the logo
<img width="1568" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/555e8fea-2220-41bf-9f3d-1452c055df2f">

### 5. blog menu modification
blog 里面 Recent posts  左侧菜单顺序乱的 
The order of the menu on the left side of Recent posts in the blog is out of order
* 点击这篇文章Recent posts 顺序正常 / Click on this articleRecent posts order is normal
<img width="1778" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/14f0df9a-0bc0-4294-a956-605aa2c40f10">

* 点击这篇文章Recent posts 乱的/ Click on this articleRecent posts messy
<img width="1769" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/d421a04b-3fa0-4cce-9b3b-29bd93509503">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by limingoo** [comment]
I want to fix issue 66

**Comment by lepen-yang** [comment]
关于第一个问题，本地启动服务不支持切换语言，因为 start 命令并不会生成 其他特定语言的文件，build 出来的则没有问题
<img width="377" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/46127018/b3868f2e-3b9c-4747-9b7e-2901e1b7b728">

**Comment by dlimeng** [comment]
> 关于第一个问题，本地启动服务不支持切换语言，因为 start 命令并不会生成 其他特定语言的文件，build 出来的则没有问题 <img alt="image" width="377" src="https://user-images.githubusercontent.com/46127018/257389367-b3868f2e-3b9c-4747-9b7e-2901e1b7b728.png">

LGTM
