### ISSUE TITLE
[Feature][SolidUI-Web] Support text input box   generate html  dynamic rendering

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#74]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

#73

/solidui/models/generate Receive interface output html, front-end rendering

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yxjun1984** [comment]
logo:
![image](https://github.com/CloudOrc/SolidUI/assets/62503859/9e81533b-2496-493d-a2d7-01da23b99fd9)
名称：企牛控股
网址：https://www.qiniukonggu.com/
联系方式：yxjun1984@gmail.com
使用场景：经营分析、营销分析

**Comment by dlimeng** [comment]
> logo: ![image](https://user-images.githubusercontent.com/62503859/251032568-9e81533b-2496-493d-a2d7-01da23b99fd9.png) 名称：企牛控股 网址：https://www.qiniukonggu.com/ 联系方式：[yxjun1984@gmail.com](mailto:yxjun1984@gmail.com) 使用场景：经营分析、营销分析

hello , move to https://github.com/CloudOrc/SolidUI/issues/1
