### ISSUE TITLE
[Feature][SolidUI-Web]   Chat entry support select database

### ISSUE THREAD

**Issue by dlimeng** [CloudOrc/SolidUI#81]
### Search before asking

- [X] I had searched in the [issues](https://github.com/CloudOrc/SolidUI/issues) and found no similar feature requirement.

### Problem Description

#82 

Go to scene -> page, select modelui, there is an icon pop-up window in the bottom right corner, choose the database id, library, table, after clicking the confirm button, append the table's json data in the prompt input box
进入场景-> 页 ，选择modelui , 右下角有个icon弹窗，选择数据库id、库、表，确认按钮后，在提示词输入框追加表的json数据

The specific implementation issues and prototypes mirror each other
具体实现issue和原型互相映照

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by liangxm-swan** [comment]
I will try my best to do it，please assign to me

**Comment by dlimeng** [comment]
Icon Text Obstruction
图标文字遮挡
<img width="1782" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/6aefa05c-bfc8-41f4-8aae-ea9e7ffededc">

**Comment by dlimeng** [comment]
选择完数据库生成json，点击发送信息，没有json，具体看下录屏
After selecting the database to generate JSON, click to send information. There is no JSON. Please refer to the screen recording for details.
<img width="1788" alt="image" src="https://github.com/CloudOrc/SolidUI/assets/16789827/03f7cacc-83e1-4916-ad6d-8a39a2a559a9">

[屏幕录制2023-09-11 下午11.40.24.mov.zip](https://github.com/CloudOrc/SolidUI/files/12578094/2023-09-11.11.40.24.mov.zip)
